Repository rudderlabs/rudder-sdk-ios, pull requests merged in 2024-01, with the labels that each got.

#433 fix: updated version of MetricsReporter in package.swift
  Package.swift
  Podfile.lock
  Rudder.podspec
  Rudder.xcodeproj/project.pbxproj
Labels: Ready for review

#435 chore(ci): change the platform from ubuntu to macOS
  .github/workflows/publish-new-release.yml
Labels: Ready for review

#436 feat: added support for gzip
  Examples/SampleSwift-iOS/SampleSwift-iOS/AppDelegate.swift
  Rudder.xcodeproj/project.pbxproj
  Sources/Classes/Common/Constants/RSConstants.swift
  Sources/Classes/Common/Extensions/Data+Gzip.swift
  Sources/Classes/Domain/Models/RSConfig.swift
  Sources/Classes/Networking/APIClient/RSServiceManager.swift
Labels: v2

#437 feat: support for data residency
  .github/workflows/build-and-quality-checks-v2.yml
  .github/workflows/check-pr-title-v2.yml
  .github/workflows/create-hotfix-branch-v2.yml
  .github/workflows/deploy-cocoapods-v2.yml
  .github/workflows/draft-new-beta-release.yml
  .github/workflows/draft-new-release-v2.yml
  .github/workflows/test-v2.yml
  Examples/SampleSwift-iOS/SampleSwift-iOS/AppDelegate.swift
  Rudder.xcodeproj/project.pbxproj
  RudderTests/BlackListedEventsTest.swift
  RudderTests/ClientTests.swift
  RudderTests/DataResidencyTests.swift
  RudderTests/DatabaseTests.swift
  RudderTests/Fixtures/ServerConfig.json
  RudderTests/Fixtures/eu-dataresidency-default-false.json
  RudderTests/Fixtures/eu-dataresidency-default-true.json
  RudderTests/Fixtures/multi-dataresidency-default-false.json
  RudderTests/Fixtures/multi-dataresidency-default-true.json
  RudderTests/Fixtures/multi-dataresidency-eu-true.json
  RudderTests/Fixtures/multi-dataresidency-us-true.json
  RudderTests/Fixtures/no-dataresidency.json
  RudderTests/Fixtures/us-dataresidency-default-false.json
  RudderTests/Fixtures/us-dataresidency-default-true.json
  RudderTests/MacOSLifeCycleEventTests.swift
  RudderTests/RSClientTests.swift.plist
  RudderTests/ServiceManagerTests.swift
  RudderTests/TestUtils.swift
  RudderTests/ThreadTests.swift
  RudderTests/WatchOSLifeCycleEventTests.swift
  RudderTests/WhiteListedEventsTests.swift
  RudderTests/iOSLifeCycleEventTests.swift
  Sources/Classes/Client/Plugins/RSContextPlugin.swift
  Sources/Classes/Client/Plugins/RSIntegrationPlugin.swift
  Sources/Classes/Client/Plugins/RudderDestinationPlugin.swift
  Sources/Classes/Client/RSClient+Plugins.swift
  Sources/Classes/Client/RSClient.swift
  Sources/Classes/Client/RSDatabaseManager.swift
  Sources/Classes/Common/Extensions/Data+Gzip.swift
  Sources/Classes/Domain/Models/Attributes/RSServerConfig.swift
  Sources/Classes/Domain/Models/RSConfig.swift
  Sources/Classes/Domain/Models/RSContext.swift
  Sources/Classes/Domain/Models/RSDBMessage.swift
  Sources/Classes/Domain/Protocols/RSDownloadServerConfig.swift
  Sources/Classes/Helpers/RSSessionStorage.swift
  Sources/Classes/Networking/APIClient/RSServiceManager.swift
  Sources/Classes/Utility/MockURLProtocol.swift
  Sources/Classes/Utility/RSUtils.swift
Labels: v2

#453 feat: add privacy manifest file to ios sdk
  Package.resolved
  Package.swift
  Podfile.lock
  PrivacyInfo.xcprivacy
  Rudder.podspec
  Rudder.xcodeproj/project.pbxproj
  Sources/Classes/RSConstants.m
Labels: v1
