Repository rudderlabs/rudder-sdk-ios, pull requests merged in 2024-04, with the labels that each got.

#458 feat: support for multiple instance
  .gitignore
  Examples/SampleApps/Swift-iOS/ViewController.swift
  Rudder.xcodeproj/project.pbxproj
  RudderCore/Sources/Core/Attributes/Configuration.swift
  RudderCore/Sources/Core/Attributes/Context.swift
  RudderCore/Sources/Core/Attributes/Message.swift
  RudderCore/Sources/Core/Attributes/Option.swift
  RudderCore/Sources/Core/Common/Constants.swift
  RudderCore/Sources/Core/Helpers/DataResidency.swift
  RudderCore/Sources/Core/Helpers/SessionStorage.swift
  RudderCore/Sources/Core/Helpers/UserDefaultsWorker.swift
  RudderCore/Sources/Core/Logger/LogMessages.swift
  RudderCore/Sources/Core/ObjC/ObjCRSClient.swift
  RudderCore/Sources/Core/Plugins/ContextPlugin.swift
  RudderCore/Sources/Core/Plugins/IntegrationPlugin.swift
  RudderCore/Sources/Core/RudderCore.swift
  RudderCore/Sources/Core/RudderProtocol.swift
  RudderCore/Sources/Core/SourceConfigDownload/SourceConfigDownload.swift
  RudderCore/Sources/Core/SourceConfigDownload/SourceConfigDownloadWorker.swift
  RudderCore/Sources/Core/Storage/Migration/StorageMigration.swift
  RudderCore/Sources/Core/Storage/Migration/StorageMigrator.swift
  RudderCore/Sources/RSClient.swift
  RudderCore/Tests/Core/ClientTests.swift
  RudderCore/Tests/Core/Networking/ServiceManagerTests.swift
  RudderCore/Tests/Core/Plugins/EventFilteringTests.swift
  RudderCore/Tests/Core/Plugins/ReplayQueuePluginTests.swift
  RudderCore/Tests/Core/Plugins/UserSessionPluginTests.swift
  RudderCore/Tests/Core/SourceConfigDownload/SourceConfigDownloadTests.swift
  RudderCore/Tests/Core/SourceConfigDownload/SourceConfigDownloadWorkerTests.swift
  RudderCore/Tests/Core/Storage/StorageMigratorTests.swift
  RudderCore/Tests/Mocks/CoreMocks.swift
  RudderCore/Tests/Mocks/RSClientMock.swift
  RudderTests/Core/DataResidencyTests.swift
  RudderTests/Mocks/NOLogger.swift
Labels: v2

#499 fix: resolve issue with privacy manifest file not being generated when consumed through SPM
  Package.swift
  Rudder.podspec
  Sources/Resources/PrivacyInfo.xcprivacy
Labels: Ready for review, v1

#496 feat: add privacy manifest file support for ios v2 sdk
  Package.swift
  Podfile.lock
  Rudder.podspec
  Sources/Classes/Common/Constants/RSConstants.swift
  Sources/Resources/PrivacyInfo.xcprivacy
Labels: Ready for review, v2

#500 ci: change the PR reviewer to sdk team
  .github/workflows/draft-new-release.yml
  .github/workflows/publish-new-release.yml
Labels: Ready for review, v1

#503 ci: change the PR reviewer to the sdk team
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/draft-new-release-v2.yml
Labels: Ready for review, v2

#505 chore(release): pulling release/2.4.4-beta into master-v2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/draft-new-release-v2.yml
  CHANGELOG.md
  Package.swift
  Podfile.lock
  README.md
  Rudder.podspec
  Sources/Classes/Common/Constants/RSConstants.swift
  Sources/Classes/Common/Constants/RSVersion.swift
  Sources/Resources/PrivacyInfo.xcprivacy
  package.json
  sonar-project.properties
Labels: Ready for review, v2

#509 fix: remove tracking domain url from Privacy Manifest file
  Sources/Resources/PrivacyInfo.xcprivacy
Labels: Ready for review, v1

#514 fix: remove tracking domain url from Privacy Manifest file in v2
  Podfile.lock
  Sources/Resources/PrivacyInfo.xcprivacy
Labels: Ready for review, v2

#516 chore(release): pulling release/2.5.1-beta into master-v2
  CHANGELOG.md
  Podfile.lock
  README.md
  Sources/Classes/Common/Constants/RSVersion.swift
  Sources/Resources/PrivacyInfo.xcprivacy
  package.json
  sonar-project.properties
Labels: Ready for review, v2
