Repository rudderlabs/rudder-sdk-ios, pull requests merged in 2024-06, with the labels that each got.

#521 ci: change the latest platform to macos-latest-large
  .github/workflows/test.yml
Labels: Ready for review, v1

#520 feat: add support for deep link tracking
  Examples/RudderConfig/RudderConfig.plist
  Examples/RudderSampleAppObjC/RudderSampleAppObjC.xcodeproj/project.pbxproj
  Examples/RudderSampleAppObjC/RudderSampleAppObjC/RudderSampleAppObjC-Info.plist
  Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m
  Examples/RudderSampleAppObjC/RudderSampleAppObjC/en.lproj/InfoPlist.strings
  Examples/RudderSampleAppSwift/RudderSampleAppSwift.xcodeproj/project.pbxproj
  Examples/RudderSampleAppSwift/RudderSampleAppSwift/Info.plist
  Examples/RudderSampleAppSwift/RudderSampleAppSwift/SceneDelegate.swift
  Podfile.lock
  Sources/Classes/Headers/Public/RSClient.h
  Sources/Classes/Headers/Public/RSUtils.h
  Sources/Classes/RSClient.m
  Sources/Classes/RSUtils.m
Labels: v1

#518 chore: update pr_reviewer and assignees
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/draft-new-release-v2.yml
Labels: Ready for review
