Repository rudderlabs/rudder-sdk-ios, pull requests merged in 2024-02, with the labels that each got.

#448 fix: sending detailed device model info
  Sources/Classes/RSDeviceInfo.m
Labels: Ready for review

#456 ci: fixed failing draft new beta release workflow
  .github/workflows/draft-new-beta-release.yml
Labels: Ready for review

#447 fix: handling the serialization of special floating point values while serializing any object
  Examples/RudderSampleApptvOSObjC/RudderSampleApptvOSObjC.xcodeproj/project.pbxproj
  Examples/RudderSampleAppwatchOSObjC/RudderSampleAppwatchOSObjC.xcodeproj/project.pbxproj
  Podfile.lock
  Rudder.xcodeproj/project.pbxproj
  Sources/Classes/Headers/Public/RSUtils.h
  Sources/Classes/RSCloudModeManager.m
  Sources/Classes/RSContext.m
  Sources/Classes/RSDBPersistentManager.m
  Sources/Classes/RSDeviceModeManager.m
  Sources/Classes/RSDeviceModeTransformationManager.m
  Sources/Classes/RSEventRepository.m
  Sources/Classes/RSMessage.m
  Sources/Classes/RSNetwork.m
  Sources/Classes/RSPreferenceManager.m
  Sources/Classes/RSServerConfigManager.m
  Sources/Classes/RSUtils.m
  Tests/RudderUtilsTest.swift
Labels: Ready for review

#460 fix: nil check errors after de-serialization
  Sources/Classes/RSContext.m
  Sources/Classes/RSDeviceModeTransformationManager.m
Labels: Ready for review

#464 chore(ci): fix publish new release github action
  .github/workflows/publish-new-release.yml
Labels: Ready for review, v1

#465 fix: correct file name of LICENSE.md file in Podspec
  Podfile.lock
  Rudder.podspec
Labels: Ready for review, v1

#438 feat: support for user-choice storage
  Rudder.xcodeproj/project.pbxproj
  RudderTests/DatabaseTests.swift
  RudderTests/StorageTests.swift
  Sources/Classes/Client/Plugins/RudderDestinationPlugin.swift
  Sources/Classes/Client/RSClient.swift
  Sources/Classes/Client/RSDatabaseManager.swift
  Sources/Classes/Domain/Enums/RSInternalErrors.swift
  Sources/Classes/Domain/Models/RSConfig.swift
  Sources/Classes/Domain/Models/RSMessageEntity.swift
  Sources/Classes/Domain/Protocols/RSMessage.swift
  Sources/Classes/Helpers/Logger.swift
  Sources/Classes/Helpers/Platforms/Vendors/AppleUtils.swift
  Sources/Classes/Helpers/Platforms/Vendors/Vendor.swift
  Sources/Classes/Storage/Database.swift
  Sources/Classes/Storage/DefaultDatabase.swift
  Sources/Classes/Storage/DefaultStorage.swift
  Sources/Classes/Storage/Storage.swift
  Sources/Classes/Storage/StorageWorker.swift
  Sources/Classes/Utility/RSUtils.swift
Labels: v2

#454 fix: added a persistence layer over keys stored in standard defaults by rudderstack
  Podfile.lock
  Rudder.xcodeproj/project.pbxproj
  Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-iOS.xcscheme
  Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-tvOS.xcscheme
  Rudder.xcodeproj/xcshareddata/xcschemes/RudderTests-watchOS.xcscheme
  Sources/Classes/Headers/Public/RSDefaultsPersistence.h
  Sources/Classes/Headers/Public/RSEventRepository.h
  Sources/Classes/Headers/Public/RSPreferenceManager.h
  Sources/Classes/Headers/Public/RSUtils.h
  Sources/Classes/RSDefaultsPersistence.m
  Sources/Classes/RSEventRepository.m
  Sources/Classes/RSPreferenceManager.m
  Sources/Classes/RSUtils.m
  Tests/DefaultsPersistenceTests.swift
Labels: Ready for review, v1
